### ISSUE TITLE
Bug: Can see others' comments without permission

### ISSUE THREAD

**Issue by cagdas001** [topcoder-platform/beta-testing-forums#121]
As you can see below, I don't have permission on any of the challenges & dicussion this user commented on.

![no-permission](https://user-images.githubusercontent.com/28513447/109333511-9962ee80-7870-11eb-98a3-85c7b8b80108.png)

Click the **Comments** link at left. You'll see all the comments

![chrome_2021-02-26_20-24-55](https://user-images.githubusercontent.com/28513447/109333707-d3cc8b80-7870-11eb-8690-94a170903a50.png)

**Comment by cagdas001** [comment]
UPDATE: Sorry, false alarm. This is not a bug

**Comment by hokienick** [comment]
Not a bug
